/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307200636 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticNorthwind_dbo_Order_Details_Extended(fillPrimaryKey = false) {
	let retObj = new Northwind_dbo_Order_Details_Extended_IR();
	retObj.OrderID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.ProductID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.ProductName = 'uZxfmTUkwPQJ88 noAcIOYNLR7g8RvHLHhVuWLUu';
	retObj.UnitPrice = 0.5456840298963803;
	retObj.Quantity = 11141;
	retObj.Discount = 0.86433774;
	retObj.ExtendedPrice = 0.012296415569239105;
	return retObj;
}
