/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307202958 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticXE_HR_PACKAGE1_RETURNSTRINGPROC(fillPrimaryKey = false) {
	var retObj = new XE_HR_PACKAGE1_RETURNSTRINGPROC_OM_IR();
		// Output parameters
	retObj.CONVERTED_TO_VARCHAR2 = '04h5l6AXZnBQQhpuHvUJtnRC8M3g9mFnc6oXL7qOjRvCe5FS86yjDwHqaFjypHdHmy7KdzIrcoYArYdT 1CkOWPB5igtD9nkjhrc';
	return retObj;
}
