/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307200636 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using Northwind_BackEndSqlEntities.Entities;
namespace Northwind_BackEndDatabaseClientTests.HydratedStaticEntities;
public partial class Northwind_HydratedStaticEntities 
{
	public Northwind_dbo_Suppliers GetHydratedStaticNorthwind_dbo_Suppliers(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Suppliers();
		retObj.SupplierID = (fillPrimaryKey ? Convert.ToInt32(1) : 0);
		retObj.CompanyName = "4tcz2CU7wy90ND0nmpE6VxpohWfH89Az9pTNspof";
		retObj.ContactName = "JYxrZYoeWuynTpdtLunFvFJfOPCJAb";
		retObj.ContactTitle = "tO5uEihJ g2hOb04Jg7yP8fxxoMwO9";
		retObj.Address = "BDg5dpF8alQtqAvyymFBSEKIosXZVNj4JyaBDPSXd77YlcnmfaU2HIZsvpZe";
		retObj.City = "lPGzUGmDc5ioEqS";
		retObj.Region = "kRerNt2MdbXgJDH";
		retObj.PostalCode = "YqQoD6XuaL";
		retObj.Country = "6BQDOZKYAWZcb2n";
		retObj.Phone = "fmnHhY2OXe4Dec8oj8OgOS09";
		retObj.Fax = "xSXYDsk8CbkGWT1gqTZgn Zw";
		retObj.HomePage = "PSYRzXy4bRJQjxDy9iwv2D1ewmljLutdJJRd0KAvik CUswwmgoAXGvXn2yLXKi02SeTMItJANfyg5Gi1UnuQ2JsI RcFu1 W2Dt";
		return retObj;
	}
}
