/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307200636 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
// For reads only
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;
namespace Northwind_Common.IndirectReferenceTransformerModels;
/// <summary>
/// Sql Entity Description: Indirect Referenced Model Description: N/A
/// </summary>
public class Northwind_dbo_Quarterly_Orders_IR
{
	public Northwind_dbo_Quarterly_Orders_IR() 
	{
	} 
	public Northwind_dbo_Quarterly_Orders_IR(
		String? customerID_,
		String? companyName_,
		String? city_,
		String? country_
	)
	{
		_customerID = customerID_;
		CustomerID_OriginalValue = customerID_;
		_companyName = companyName_;
		CompanyName_OriginalValue = companyName_;
		_city = city_;
		City_OriginalValue = city_;
		_country = country_;
		Country_OriginalValue = country_;
	}
	[JsonConstructor]
	public Northwind_dbo_Quarterly_Orders_IR(
		String? CustomerID,
		String? CustomerID_OriginalValue,
		Boolean CustomerID_HasBeenChanged,
		String? CompanyName,
		String? CompanyName_OriginalValue,
		Boolean CompanyName_HasBeenChanged,
		String? City,
		String? City_OriginalValue,
		Boolean City_HasBeenChanged,
		String? Country,
		String? Country_OriginalValue,
		Boolean Country_HasBeenChanged
	)
	{
		this.CustomerID = CustomerID;
		this.CustomerID_OriginalValue = CustomerID_OriginalValue;
		this.CustomerID_HasBeenChanged = CustomerID_HasBeenChanged;
		this.CompanyName = CompanyName;
		this.CompanyName_OriginalValue = CompanyName_OriginalValue;
		this.CompanyName_HasBeenChanged = CompanyName_HasBeenChanged;
		this.City = City;
		this.City_OriginalValue = City_OriginalValue;
		this.City_HasBeenChanged = City_HasBeenChanged;
		this.Country = Country;
		this.Country_OriginalValue = Country_OriginalValue;
		this.Country_HasBeenChanged = Country_HasBeenChanged;
	}
	/// <summary>
	/// SQL Column Description: N/A
	/// </summary>
	public String? CustomerID
	{
		get => _customerID;
		set
		{
			_customerID = value;
			CustomerID_HasBeenChanged = _customerID == CustomerID_OriginalValue ? false : true;
		}
	}
	private String? _customerID;
	public String? CustomerID_OriginalValue { get; private set; }
	public Boolean CustomerID_HasBeenChanged { get; private set; }
	/// <summary>
	/// SQL Column Description: N/A
	/// </summary>
	public String? CompanyName
	{
		get => _companyName;
		set
		{
			_companyName = value;
			CompanyName_HasBeenChanged = _companyName == CompanyName_OriginalValue ? false : true;
		}
	}
	private String? _companyName;
	public String? CompanyName_OriginalValue { get; private set; }
	public Boolean CompanyName_HasBeenChanged { get; private set; }
	/// <summary>
	/// SQL Column Description: N/A
	/// </summary>
	public String? City
	{
		get => _city;
		set
		{
			_city = value;
			City_HasBeenChanged = _city == City_OriginalValue ? false : true;
		}
	}
	private String? _city;
	public String? City_OriginalValue { get; private set; }
	public Boolean City_HasBeenChanged { get; private set; }
	/// <summary>
	/// SQL Column Description: N/A
	/// </summary>
	public String? Country
	{
		get => _country;
		set
		{
			_country = value;
			Country_HasBeenChanged = _country == Country_OriginalValue ? false : true;
		}
	}
	private String? _country;
	public String? Country_OriginalValue { get; private set; }
	public Boolean Country_HasBeenChanged { get; private set; }
}
