/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307200636 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;
namespace Northwind_Common.IndirectReferenceTransformerModels;
/// <summary>
/// Sql Entity Description: Model Description: Stored Procedure Output Model
/// </summary>
public class Northwind_dbo_Employee_Sales_by_Country_OM_IR
{
	public Northwind_dbo_Employee_Sales_by_Country_OM_IR() 
	{
	} 
	public Northwind_dbo_Employee_Sales_by_Country_OM_IR(
		String? country_,
		String? lastName_,
		String? firstName_,
		DateTime? shippedDate_,
		String? orderID_IR_,
		Decimal? saleAmount_
	)
	{
		Country = country_;
		LastName = lastName_;
		FirstName = firstName_;
		ShippedDate = shippedDate_;
		OrderID_IR = orderID_IR_;
		SaleAmount = saleAmount_;
	}
	[JsonConstructor]
	public Northwind_dbo_Employee_Sales_by_Country_OM_IR(
		String? Country,
		String? Country_OriginalValue,
		Boolean Country_HasBeenChanged,
		String? LastName,
		String? LastName_OriginalValue,
		Boolean LastName_HasBeenChanged,
		String? FirstName,
		String? FirstName_OriginalValue,
		Boolean FirstName_HasBeenChanged,
		DateTime? ShippedDate,
		DateTime? ShippedDate_OriginalValue,
		Boolean ShippedDate_HasBeenChanged,
		String? OrderID_IR,
		String? OrderID_IR_OriginalValue,
		Boolean OrderID_IR_HasBeenChanged,
		Decimal? SaleAmount,
		Decimal? SaleAmount_OriginalValue,
		Boolean SaleAmount_HasBeenChanged
	)
	{
		this.Country = Country;
		this.Country_OriginalValue = Country_OriginalValue;
		this.Country_HasBeenChanged = Country_HasBeenChanged;
		this.LastName = LastName;
		this.LastName_OriginalValue = LastName_OriginalValue;
		this.LastName_HasBeenChanged = LastName_HasBeenChanged;
		this.FirstName = FirstName;
		this.FirstName_OriginalValue = FirstName_OriginalValue;
		this.FirstName_HasBeenChanged = FirstName_HasBeenChanged;
		this.ShippedDate = ShippedDate;
		this.ShippedDate_OriginalValue = ShippedDate_OriginalValue;
		this.ShippedDate_HasBeenChanged = ShippedDate_HasBeenChanged;
		this.OrderID_IR = OrderID_IR;
		this.OrderID_IR_OriginalValue = OrderID_IR_OriginalValue;
		this.OrderID_IR_HasBeenChanged = OrderID_IR_HasBeenChanged;
		this.SaleAmount = SaleAmount;
		this.SaleAmount_OriginalValue = SaleAmount_OriginalValue;
		this.SaleAmount_HasBeenChanged = SaleAmount_HasBeenChanged;
	}
	public String? Country
	{
		get => _country;
		set
		{
			_country = value;
			Country_HasBeenChanged = _country == Country_OriginalValue ? false : true;
		}
	}
	private String? _country;
	public String? Country_OriginalValue { get; private set; }
	public Boolean Country_HasBeenChanged { get; private set; }
	public String? LastName
	{
		get => _lastName;
		set
		{
			_lastName = value;
			LastName_HasBeenChanged = _lastName == LastName_OriginalValue ? false : true;
		}
	}
	private String? _lastName;
	public String? LastName_OriginalValue { get; private set; }
	public Boolean LastName_HasBeenChanged { get; private set; }
	public String? FirstName
	{
		get => _firstName;
		set
		{
			_firstName = value;
			FirstName_HasBeenChanged = _firstName == FirstName_OriginalValue ? false : true;
		}
	}
	private String? _firstName;
	public String? FirstName_OriginalValue { get; private set; }
	public Boolean FirstName_HasBeenChanged { get; private set; }
	public DateTime? ShippedDate
	{
		get => _shippedDate;
		set
		{
			_shippedDate = value;
			ShippedDate_HasBeenChanged = _shippedDate == ShippedDate_OriginalValue ? false : true;
		}
	}
	private DateTime? _shippedDate;
	public DateTime? ShippedDate_OriginalValue { get; private set; }
	public Boolean ShippedDate_HasBeenChanged { get; private set; }
	public String? OrderID_IR
	{
		get => _orderID_IR;
		set
		{
			_orderID_IR = value;
			OrderID_IR_HasBeenChanged = _orderID_IR == OrderID_IR_OriginalValue ? false : true;
		}
	}
	private String? _orderID_IR;
	public String? OrderID_IR_OriginalValue { get; private set; }
	public Boolean OrderID_IR_HasBeenChanged { get; private set; }
	public Decimal? SaleAmount
	{
		get => _saleAmount;
		set
		{
			_saleAmount = value;
			SaleAmount_HasBeenChanged = _saleAmount == SaleAmount_OriginalValue ? false : true;
		}
	}
	private Decimal? _saleAmount;
	public Decimal? SaleAmount_OriginalValue { get; private set; }
	public Boolean SaleAmount_HasBeenChanged { get; private set; }
}
