/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307200541 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using Northwind_BackEndSqlEntities.Entities;
namespace Northwind_BackEndDatabaseClientTests.HydratedStaticEntities;
public partial class Northwind_HydratedStaticEntities 
{
	public Northwind_dbo_Quarterly_Orders GetHydratedStaticNorthwind_dbo_Quarterly_Orders(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Quarterly_Orders();
		retObj.CustomerID = "q6uig";
		retObj.CompanyName = "8OIsd4NfBUsk7g0S9XpKL27GpOXSKLrcaZbeGbh7";
		retObj.City = "0Wq2D4Wq4uHNG8r";
		retObj.Country = "2R9OxxUGgfSAq67";
		return retObj;
	}
}
