/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307200541 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using Northwind_BackEndSqlEntities.Entities;
namespace Northwind_BackEndDatabaseClientTests.HydratedStaticEntities;
public partial class Northwind_HydratedStaticEntities 
{
	public Northwind_dbo_EmployeeTerritories GetHydratedStaticNorthwind_dbo_EmployeeTerritories(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_EmployeeTerritories();
		retObj.EmployeeID = (fillPrimaryKey ? Convert.ToInt32(1) : 0);
		retObj.TerritoryID = (fillPrimaryKey ? "WmlvsiKv829012gPt594" : String.Empty);
		// Foreign key entities
		retObj.FK_EmployeeTerritories_Employees_Ref = GetHydratedStaticNorthwind_dbo_Employees();
		retObj.FK_EmployeeTerritories_Territories_Ref = GetHydratedStaticNorthwind_dbo_Territories();
		return retObj;
	}
}
