/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307202958 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;
namespace XE_HR_Common.IndirectReferenceTransformerModels;
/// <summary>
/// Sql Entity Description: Model Description: Stored Procedure Output Model
/// </summary>
public class XE_HR_PACKAGE1_RETURNSTRINGPROC_OM_IR
{
	public XE_HR_PACKAGE1_RETURNSTRINGPROC_OM_IR() 
	{
	} 
	public XE_HR_PACKAGE1_RETURNSTRINGPROC_OM_IR(
		String? cONVERTED_TO_VARCHAR2_
	)
	{
		CONVERTED_TO_VARCHAR2 = cONVERTED_TO_VARCHAR2_;
	}
	[JsonConstructor]
	public XE_HR_PACKAGE1_RETURNSTRINGPROC_OM_IR(
		String? CONVERTED_TO_VARCHAR2,
		String? CONVERTED_TO_VARCHAR2_OriginalValue,
		Boolean CONVERTED_TO_VARCHAR2_HasBeenChanged
	)
	{
		this.CONVERTED_TO_VARCHAR2 = CONVERTED_TO_VARCHAR2;
		this.CONVERTED_TO_VARCHAR2_OriginalValue = CONVERTED_TO_VARCHAR2_OriginalValue;
		this.CONVERTED_TO_VARCHAR2_HasBeenChanged = CONVERTED_TO_VARCHAR2_HasBeenChanged;
	}
	public String? CONVERTED_TO_VARCHAR2
	{
		get => _cONVERTED_TO_VARCHAR2;
		set
		{
			_cONVERTED_TO_VARCHAR2 = value;
			CONVERTED_TO_VARCHAR2_HasBeenChanged = _cONVERTED_TO_VARCHAR2 == CONVERTED_TO_VARCHAR2_OriginalValue ? false : true;
		}
	}
	private String? _cONVERTED_TO_VARCHAR2;
	public String? CONVERTED_TO_VARCHAR2_OriginalValue { get; private set; }
	public Boolean CONVERTED_TO_VARCHAR2_HasBeenChanged { get; private set; }
}
