/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307202958 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;
namespace XE_HR_Common.IndirectReferenceTransformerModels;
/// <summary>
/// Sql Entity Description: Indirect Referenced Model Description: country table. Contains 25 rows. References with locations table.
/// </summary>
public class XE_HR_COUNTRIES_IR
{
	public XE_HR_COUNTRIES_IR() 
	{
	} 
	public XE_HR_COUNTRIES_IR(
		String? cOUNTRY_ID_,
		String? cOUNTRY_NAME_,
		String? rEGION_ID_IR_
	)
	{
		_cOUNTRY_ID = cOUNTRY_ID_;
		COUNTRY_ID_OriginalValue = cOUNTRY_ID_;
		_cOUNTRY_NAME = cOUNTRY_NAME_;
		COUNTRY_NAME_OriginalValue = cOUNTRY_NAME_;
		_rEGION_ID_IR = rEGION_ID_IR_;
		REGION_ID_IR_OriginalValue = rEGION_ID_IR_;
		PrimaryKeyEncryptedForUpdateDeleteIdentification = cOUNTRY_ID_;
	}
	[JsonConstructor]
	public XE_HR_COUNTRIES_IR(
		String COUNTRY_ID,
		String COUNTRY_ID_OriginalValue,
		Boolean COUNTRY_ID_HasBeenChanged,
		String? COUNTRY_NAME,
		String? COUNTRY_NAME_OriginalValue,
		Boolean COUNTRY_NAME_HasBeenChanged,
		String? REGION_ID_IR,
		String? REGION_ID_IR_OriginalValue,
		Boolean REGION_ID_IR_HasBeenChanged,
		String? PrimaryKeyEncryptedForUpdateDeleteIdentification,
		String? PrimaryKeyHashedForUniqueObjectComparison
	)
	{
		this.COUNTRY_ID = COUNTRY_ID;
		this.COUNTRY_ID_OriginalValue = COUNTRY_ID_OriginalValue;
		this.COUNTRY_ID_HasBeenChanged = COUNTRY_ID_HasBeenChanged;
		this.COUNTRY_NAME = COUNTRY_NAME;
		this.COUNTRY_NAME_OriginalValue = COUNTRY_NAME_OriginalValue;
		this.COUNTRY_NAME_HasBeenChanged = COUNTRY_NAME_HasBeenChanged;
		this.REGION_ID_IR = REGION_ID_IR;
		this.REGION_ID_IR_OriginalValue = REGION_ID_IR_OriginalValue;
		this.REGION_ID_IR_HasBeenChanged = REGION_ID_IR_HasBeenChanged;
		this.PrimaryKeyEncryptedForUpdateDeleteIdentification = PrimaryKeyEncryptedForUpdateDeleteIdentification;
		this.PrimaryKeyHashedForUniqueObjectComparison = PrimaryKeyHashedForUniqueObjectComparison;
	}
	/// <summary>
	/// SQL Column Description: Primary key encrypted value for update and delete identification purposes
	/// </summary>
	public String? PrimaryKeyEncryptedForUpdateDeleteIdentification { get; set; }
	/// <summary>
	/// SQL Column Description: Primary key hashed value for uniue object comparison purposes
	/// </summary>
	public String? PrimaryKeyHashedForUniqueObjectComparison { get; set; }
	/// <summary>
	/// SQL Column Description: Primary key of countries table.
	/// </summary>
	public String? COUNTRY_ID
	{
		get => _cOUNTRY_ID;
		set
		{
			_cOUNTRY_ID = value;
			COUNTRY_ID_HasBeenChanged = _cOUNTRY_ID == COUNTRY_ID_OriginalValue ? false : true;
		}
	}
	private String? _cOUNTRY_ID;
	public String? COUNTRY_ID_OriginalValue  { get; private set; }
	public Boolean COUNTRY_ID_HasBeenChanged  { get; private set; }
	/// <summary>
	/// SQL Column Description: Country name
	/// </summary>
	public String? COUNTRY_NAME
	{
		get => _cOUNTRY_NAME;
		set
		{
			_cOUNTRY_NAME = value;
			COUNTRY_NAME_HasBeenChanged = _cOUNTRY_NAME == COUNTRY_NAME_OriginalValue ? false : true;
		}
	}
	private String? _cOUNTRY_NAME;
	public String? COUNTRY_NAME_OriginalValue  { get; private set; }
	public Boolean COUNTRY_NAME_HasBeenChanged  { get; private set; }
	/// <summary>
	/// SQL Column Description: Region ID for the country. Foreign key to region_id column in the departments table.
	/// </summary>
	public String? REGION_ID_IR
	{
		get => _rEGION_ID_IR;
		set
		{
			_rEGION_ID_IR = value;
			REGION_ID_IR_HasBeenChanged = _rEGION_ID_IR == REGION_ID_IR_OriginalValue ? false : true;
		}
	}
	private String? _rEGION_ID_IR;
	public String? REGION_ID_IR_OriginalValue { get; private set; }
	public Boolean REGION_ID_IR_HasBeenChanged { get; private set; }
	// Foreign key entities
	public virtual XE_HR_REGIONS_IR? COUNTR_REG_FK_Ref_IR { get; set; }
	/// <summary>
	/// Entities that reference this entity by foreign key
	/// </summary>
	/// <example>null</example>
	public virtual ICollection<XE_HR_LOCATIONS_IR>?LOC_C_ID_FK_RefBy_IR { get; set; } = new HashSet<XE_HR_LOCATIONS_IR>();
	/// <summary>
	/// Foreign key entity
	/// </summary>
	/// <example>null</example>
}
