/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307200541 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedStaticNorthwind_dbo_Alphabetical_list_of_products(fillPrimaryKey = false) {
	let retObj = new Northwind_dbo_Alphabetical_list_of_products_IR();
	retObj.ProductID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.ProductName = 'CEyk SAc90kKY4sSrKDCBWw8tVEeD7I VTzwt2OW';
	retObj.SupplierID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.CategoryID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.QuantityPerUnit = 'jpV3sh6DL1Tl6JRPJZ1b';
	retObj.UnitPrice = 0.27351513048883647;
	retObj.UnitsInStock = 7998;
	retObj.UnitsOnOrder = -16565;
	retObj.ReorderLevel = -15264;
	retObj.Discontinued = false;
	retObj.CategoryName = '9zsBVFCvqqLu52L';
	return retObj;
}
