/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307202757 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Free Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use for evaluation purposes only. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using XE_HR_BackEndDatabaseClient.Repositories;
using XE_HR_BackEndSqlEntities.Entities;
namespace XE_HR_BackEndCommon.RequestHandlers;
public interface IXE_HR_DEPARTMENTS_RequestHandler
{
	//Main Handlers
	Task<IEnumerable<XE_HR_DEPARTMENTS>?> HandleGetAll();
	Task<IEnumerable<XE_HR_DEPARTMENTS>?> HandleGetByDEPARTMENT_ID(Int32 dEPARTMENT_ID);
	Task<IEnumerable<XE_HR_DEPARTMENTS>?> HandleGetByLOCATION_ID(Int32? lOCATION_ID);
	Task<XE_HR_DEPARTMENTS?> HandleCreate(XE_HR_DEPARTMENTS entity);
	Task HandleUpdateByDEPARTMENT_ID(Int32 dEPARTMENT_ID, XE_HR_DEPARTMENTS entity);
	Task HandleUpdateByLOCATION_ID(Int32? lOCATION_ID, XE_HR_DEPARTMENTS entity);
	Task HandleDeleteByDEPARTMENT_ID(Int32 dEPARTMENT_ID);
	Task HandleDeleteByLOCATION_ID(Int32? lOCATION_ID);
}
