/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307200636 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Northwind_Common.IndirectReferenceTransformerModels;
using Northwind_BackEndDatabaseClient.Repositories;
using Northwind_Common.Validators;
using Northwind_BackEndCommon.IndirectReferenceTransformers;
using Northwind_BackEndCommon.Services;
namespace Northwind_BackEndCommon.RequestHandlers;
public class Northwind_dbo_CustomerCustomerDemo_RequestHandler : INorthwind_dbo_CustomerCustomerDemo_RequestHandler
{
    private readonly ILogger<Northwind_dbo_CustomerCustomerDemo_RequestHandler> _logger;
    private readonly IEncryptionDecryptionService _encryptionDecryptionService; 
    private readonly IIRTransformers _indirectReferenceTransformers;
    private readonly INorthwind_dbo_CustomerCustomerDemo_Repository _repository;
    private readonly Northwind_dbo_CustomerCustomerDemo_IR_FluentValidator_Create _createValidator;
    private readonly Northwind_dbo_CustomerCustomerDemo_IR_FluentValidator_Read _readValidator;
    private readonly Northwind_dbo_CustomerCustomerDemo_IR_FluentValidator_Update _updateValidator;
    private readonly Northwind_dbo_CustomerCustomerDemo_IR_FluentValidator_Delete _deleteValidator;
    public Northwind_dbo_CustomerCustomerDemo_RequestHandler(
        ILogger<Northwind_dbo_CustomerCustomerDemo_RequestHandler> logger
        ,IEncryptionDecryptionService encryptionDecryptionService
        ,IIRTransformers indirectReferenceTransformers
        ,INorthwind_dbo_CustomerCustomerDemo_Repository repository 
        ,Northwind_dbo_CustomerCustomerDemo_IR_FluentValidator_Create createValidator
        ,Northwind_dbo_CustomerCustomerDemo_IR_FluentValidator_Read readValidator
        ,Northwind_dbo_CustomerCustomerDemo_IR_FluentValidator_Update updateValidator
        ,Northwind_dbo_CustomerCustomerDemo_IR_FluentValidator_Delete deleteValidator
    )
    {
        _logger = logger;
        _encryptionDecryptionService = encryptionDecryptionService;
        _indirectReferenceTransformers = indirectReferenceTransformers;
        _repository = repository;
        _createValidator = createValidator;
        _readValidator = readValidator;
        _updateValidator = updateValidator;
        _deleteValidator = deleteValidator;
    }
	//Main Handlers
	public async Task<IEnumerable<Northwind_dbo_CustomerCustomerDemo_IR>?> HandleGetAll()
	{
		await PreHandleGetAll();
		var retData = await _repository.GetAll();
		await PostHandleGetAll();
		return retData == null || !retData.Any() ? Enumerable.Empty<Northwind_dbo_CustomerCustomerDemo_IR>() : retData.Select(x => _indirectReferenceTransformers.ToIndirectModel(x)!).ToList();
	}
	public async Task<IEnumerable<Northwind_dbo_CustomerCustomerDemo_IR>?> HandleGetByCustomerIDAndCustomerTypeID(String customerID, String customerTypeID)
	{
		await PreHandleGetByCustomerIDAndCustomerTypeID(customerID, customerTypeID);
		var retData = await _repository.GetByCustomerIDAndCustomerTypeID((customerID), (customerTypeID));
		await PostHandleGetByCustomerIDAndCustomerTypeID(customerID, customerTypeID);
		return retData == null || !retData.Any() ? Enumerable.Empty<Northwind_dbo_CustomerCustomerDemo_IR>() : retData.Select(x => _indirectReferenceTransformers.ToIndirectModel(x)!).ToList();
	}
	public async Task<Northwind_dbo_CustomerCustomerDemo_IR?> HandleCreate<T>(T irModel) where T : Northwind_dbo_CustomerCustomerDemo_IR
	{
		var entity = _indirectReferenceTransformers.ToEntity(irModel);
		await PreHandleCreate(irModel);
		entity = await _repository.Create(entity!);
		if (entity != null) 
		{
			await PostHandleCreate(irModel);
			return _indirectReferenceTransformers.ToIndirectModel(entity!);
		}
		else
			return null;
	}
	public async Task HandleUpdateByCustomerIDAndCustomerTypeID<T>(String customerID, String customerTypeID, T irModel) where T : Northwind_dbo_CustomerCustomerDemo_IR
	{
		var entity = _indirectReferenceTransformers.ToEntity(irModel);
		await PreHandleUpdateByCustomerIDAndCustomerTypeID(customerID, customerTypeID, irModel);
		await _repository.UpdateByCustomerIDAndCustomerTypeID((customerID), (customerTypeID), entity!);
		await PostHandleUpdateByCustomerIDAndCustomerTypeID(customerID, customerTypeID, irModel);
	}
	public async Task HandleDeleteByCustomerIDAndCustomerTypeID(String customerID, String customerTypeID)
	{
		await PreHandleDeleteByCustomerIDAndCustomerTypeID(customerID, customerTypeID);
		await _repository.DeleteByCustomerIDAndCustomerTypeID((customerID), (customerTypeID));
		await PostHandleDeleteByCustomerIDAndCustomerTypeID(customerID, customerTypeID);
	}
	//PreCRUD Handlers
	private async Task PreHandleGetAll()
	{
		// Add preCRUD calls/events
		// Remove the line below after adding optional async logic
		await Task.CompletedTask;
	}
	private async Task PreHandleGetByCustomerIDAndCustomerTypeID(String customerID, String customerTypeID)
	{
		// Add preCRUD calls/events
		var selectorProperties = new Northwind_dbo_CustomerCustomerDemo_IR();
		selectorProperties.CustomerID = customerID;
		selectorProperties.CustomerTypeID = customerTypeID;
		await _readValidator.ValidateModelAndThrow(selectorProperties);
	}
	private async Task PreHandleCreate(Northwind_dbo_CustomerCustomerDemo_IR irModel)
	{
		// Add preCRUD calls/events
		await _createValidator.ValidateModelAndThrow(irModel);
	}
	private async Task PreHandleUpdateByCustomerIDAndCustomerTypeID(String customerID, String customerTypeID, Northwind_dbo_CustomerCustomerDemo_IR irModel)
	{
		// Add preCRUD calls/events
		var selectorProperties = new Northwind_dbo_CustomerCustomerDemo_IR();
		selectorProperties.CustomerID = customerID;
		selectorProperties.CustomerTypeID = customerTypeID;
		await _readValidator.ValidateModelAndThrow(selectorProperties);
		await _updateValidator.ValidateModelAndThrow(irModel);
	}
	private async Task PreHandleDeleteByCustomerIDAndCustomerTypeID(String customerID, String customerTypeID)
	{
		// Add preCRUD calls/events
		var selectorProperties = new Northwind_dbo_CustomerCustomerDemo_IR();
		selectorProperties.CustomerID = customerID;
		selectorProperties.CustomerTypeID = customerTypeID;
		await _deleteValidator.ValidateModelAndThrow(selectorProperties);
	}
	//PostCRUD Handlers
	private async Task PostHandleGetAll()
	{
		// Add postCRUD calls/events
		// Remove the line below after adding optional async logic
		await Task.CompletedTask;
	}
	private async Task PostHandleGetByCustomerIDAndCustomerTypeID(String customerID, String customerTypeID)
	{
		// Add postCRUD calls/events
		// Remove the line below after adding optional async logic
		await Task.CompletedTask;
	}
	private async Task PostHandleCreate(Northwind_dbo_CustomerCustomerDemo_IR irModel)
	{
		// Add postCRUD calls/events
		// Remove the line below after adding optional async logic
		await Task.CompletedTask;
	}
	private async Task PostHandleUpdateByCustomerIDAndCustomerTypeID(String customerID, String customerTypeID, Northwind_dbo_CustomerCustomerDemo_IR irModel)
	{
		// Add postCRUD calls/events
		// Remove the line below after adding optional async logic
		await Task.CompletedTask;
	}
	private async Task PostHandleDeleteByCustomerIDAndCustomerTypeID(String customerID, String customerTypeID)
	{
		// Add postCRUD calls/events
		// Remove the line below after adding optional async logic
		await Task.CompletedTask;
	}
}
