/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307202926 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using System.ComponentModel.DataAnnotations.Schema;
namespace XE_HR_BackEndSqlEntities.Entities;
/// <summary>
/// SQL Entity Description: Table Description: Table that stores job history of the employees. If an employee changes departments within the job or changes jobs within the department, new rows get inserted into this table with old job information of the employee. Contains a complex primary key: employee_id+start_date.Contains 25 rows. References with jobs, employees, and departments tables.
/// </summary>
public class XE_HR_JOB_HISTORY 
{
	public XE_HR_JOB_HISTORY()
	{
	} 
	public XE_HR_JOB_HISTORY(
		Int32 eMPLOYEE_ID_,
		DateTime sTART_DATE_,
		DateTime eND_DATE_,
		String jOB_ID_,
		Int32? dEPARTMENT_ID_
	)
	{
		EMPLOYEE_ID = eMPLOYEE_ID_;
		START_DATE = sTART_DATE_;
		END_DATE = eND_DATE_;
		JOB_ID = jOB_ID_;
		DEPARTMENT_ID = dEPARTMENT_ID_;
	}
	/// <summary>
	/// Primary Key Column
	/// Foreign Key Column
	/// SQL Data Type: NUMBER Chars: 6 Precision: 6 Scale: 0 
	/// SQL Default Value: N/A
	/// SQL Column Description: A not null column in the complex primary key employee_id+start_date.Foreign key to employee_id column of the employee table
	/// </summary>
	public virtual Int32 EMPLOYEE_ID { get; set; }
	/// <summary>
	/// Primary Key Column
	/// SQL Data Type: DATE Chars: 0 
	/// SQL Default Value: N/A
	/// SQL Column Description: A not null column in the complex primary key employee_id+start_date. Must be less than the end_date of the job_history table. (enforced by constraint jhist_date_interval)
	/// </summary>
	public virtual DateTime START_DATE { get; set; }
	/// <summary>
	/// SQL Data Type: DATE Chars: 0 
	/// SQL Default Value: N/A
	/// SQL Column Description: Last day of the employee in this job role. A not null column. Must be greater than the start_date of the job_history table. (enforced by constraint jhist_date_interval)
	/// </summary>
	public virtual DateTime END_DATE { get; set; }
	/// <summary>
	/// Foreign Key Column
	/// SQL Data Type: VARCHAR2 Chars: 10 
	/// SQL Default Value: N/A
	/// SQL Column Description: Job role in which the employee worked in the past; foreign key to job_id column in the jobs table. A not null column.
	/// </summary>
	public virtual String JOB_ID { get; set; } = null!;
	/// <summary>
	/// Foreign Key Column
	/// SQL Data Type: NUMBER Chars: 4 Precision: 4 Scale: 0 
	/// SQL Default Value: N/A
	/// SQL Column Description: Department id in which the employee worked in the past; foreign key to deparment_id column in the departments table
	/// </summary>
	public virtual Int32? DEPARTMENT_ID { get; set; }
	/// <summary>
	/// Foreign key entity
	/// </summary>
	/// <example>null</example>
	public virtual XE_HR_DEPARTMENTS? JHIST_DEPT_FK_Ref { get; set; }
	/// <summary>
	/// Foreign key entity
	/// </summary>
	/// <example>null</example>
	public virtual XE_HR_EMPLOYEES? JHIST_EMP_FK_Ref { get; set; }
	/// <summary>
	/// Foreign key entity
	/// </summary>
	/// <example>null</example>
	public virtual XE_HR_JOBS? JHIST_JOB_FK_Ref { get; set; }
}
