/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307200636 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;
using Z.EntityFramework.Plus;
using Northwind_BackEndDatabaseClient;
using Northwind_BackEndSqlEntities.Entities;
namespace Northwind_BackEndDatabaseClient.Repositories;
public class Northwind_dbo_Customers_Repository : GenericTableRepository<Northwind_dbo_Customers>, INorthwind_dbo_Customers_Repository
{
    private readonly ILogger<Northwind_dbo_Customers_Repository> _logger;    
    public Northwind_dbo_Customers_Repository
    (
        ILogger<Northwind_dbo_Customers_Repository> logger
        ,Northwind_Context dbContext
    ) : base(dbContext)
    {
        _logger = logger;
    }
	public async Task<IEnumerable<Northwind_dbo_Customers>?> GetByCity(String? city_)
	{
		return await _dbContext.Northwind_dbo_Customers!
			.Where(x => x.City == city_)
			.AsNoTracking()
			.ToListAsync();
	}
	public async Task<IEnumerable<Northwind_dbo_Customers>?> GetByCompanyName(String companyName_)
	{
		return await _dbContext.Northwind_dbo_Customers!
			.Where(x => x.CompanyName == companyName_)
			.AsNoTracking()
			.ToListAsync();
	}
	public async Task<IEnumerable<Northwind_dbo_Customers>?> GetByCustomerID(String customerID_)
	{
		return await _dbContext.Northwind_dbo_Customers!
			.Where(x => x.CustomerID == customerID_)
			.AsNoTracking()
			.ToListAsync();
	}
	public async Task<IEnumerable<Northwind_dbo_Customers>?> GetByPostalCode(String? postalCode_)
	{
		return await _dbContext.Northwind_dbo_Customers!
			.Where(x => x.PostalCode == postalCode_)
			.AsNoTracking()
			.ToListAsync();
	}
	public async Task<IEnumerable<Northwind_dbo_Customers>?> GetByRegion(String? region_)
	{
		return await _dbContext.Northwind_dbo_Customers!
			.Where(x => x.Region == region_)
			.AsNoTracking()
			.ToListAsync();
	}
	public async Task UpdateByCity(String? city_, Northwind_dbo_Customers entity)
	{
		await _dbContext.Northwind_dbo_Customers!
			.Where(x => x.City == city_)
			.UpdateFromQueryAsync(x => new Northwind_dbo_Customers(){ CompanyName = entity.CompanyName, ContactName = entity.ContactName, ContactTitle = entity.ContactTitle, Address = entity.Address, City = entity.City, Region = entity.Region, PostalCode = entity.PostalCode, Country = entity.Country, Phone = entity.Phone, Fax = entity.Fax });
	}
	public async Task UpdateByCompanyName(String companyName_, Northwind_dbo_Customers entity)
	{
		await _dbContext.Northwind_dbo_Customers!
			.Where(x => x.CompanyName == companyName_)
			.UpdateFromQueryAsync(x => new Northwind_dbo_Customers(){ CompanyName = entity.CompanyName, ContactName = entity.ContactName, ContactTitle = entity.ContactTitle, Address = entity.Address, City = entity.City, Region = entity.Region, PostalCode = entity.PostalCode, Country = entity.Country, Phone = entity.Phone, Fax = entity.Fax });
	}
	public async Task UpdateByCustomerID(String customerID_, Northwind_dbo_Customers entity)
	{
		await _dbContext.Northwind_dbo_Customers!
			.Where(x => x.CustomerID == customerID_)
			.UpdateFromQueryAsync(x => new Northwind_dbo_Customers(){ CompanyName = entity.CompanyName, ContactName = entity.ContactName, ContactTitle = entity.ContactTitle, Address = entity.Address, City = entity.City, Region = entity.Region, PostalCode = entity.PostalCode, Country = entity.Country, Phone = entity.Phone, Fax = entity.Fax });
	}
	public async Task UpdateByPostalCode(String? postalCode_, Northwind_dbo_Customers entity)
	{
		await _dbContext.Northwind_dbo_Customers!
			.Where(x => x.PostalCode == postalCode_)
			.UpdateFromQueryAsync(x => new Northwind_dbo_Customers(){ CompanyName = entity.CompanyName, ContactName = entity.ContactName, ContactTitle = entity.ContactTitle, Address = entity.Address, City = entity.City, Region = entity.Region, PostalCode = entity.PostalCode, Country = entity.Country, Phone = entity.Phone, Fax = entity.Fax });
	}
	public async Task UpdateByRegion(String? region_, Northwind_dbo_Customers entity)
	{
		await _dbContext.Northwind_dbo_Customers!
			.Where(x => x.Region == region_)
			.UpdateFromQueryAsync(x => new Northwind_dbo_Customers(){ CompanyName = entity.CompanyName, ContactName = entity.ContactName, ContactTitle = entity.ContactTitle, Address = entity.Address, City = entity.City, Region = entity.Region, PostalCode = entity.PostalCode, Country = entity.Country, Phone = entity.Phone, Fax = entity.Fax });
	}
	public async Task DeleteByCity(String? city_)
	{
		await _dbContext.Northwind_dbo_Customers!
			.Where(x => x.City == city_)
			.DeleteFromQueryAsync();
	}
	public async Task DeleteByCompanyName(String companyName_)
	{
		await _dbContext.Northwind_dbo_Customers!
			.Where(x => x.CompanyName == companyName_)
			.DeleteFromQueryAsync();
	}
	public async Task DeleteByCustomerID(String customerID_)
	{
		await _dbContext.Northwind_dbo_Customers!
			.Where(x => x.CustomerID == customerID_)
			.DeleteFromQueryAsync();
	}
	public async Task DeleteByPostalCode(String? postalCode_)
	{
		await _dbContext.Northwind_dbo_Customers!
			.Where(x => x.PostalCode == postalCode_)
			.DeleteFromQueryAsync();
	}
	public async Task DeleteByRegion(String? region_)
	{
		await _dbContext.Northwind_dbo_Customers!
			.Where(x => x.Region == region_)
			.DeleteFromQueryAsync();
	}
}
