/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307202926 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.AspNetCore.SignalR.Client;
using XE_HR_Common.IndirectReferenceTransformerModels;
namespace XE_HR_FrontEndSignalRWebsocketClient.SignalRWebsocketClients;
public class XE_HR_REGIONS_SignalRWebsocketClient : SignalRWebsocketClientBase, IXE_HR_REGIONS_SignalRWebsocketClient, IAsyncDisposable
{
	public XE_HR_REGIONS_SignalRWebsocketClient(String hubUrl) : base(hubUrl)
    {
    }
	public async Task<IEnumerable<XE_HR_REGIONS_IR>?> GetByBestMatchedQueryPattern(XE_HR_REGIONS_IR input)
	{
		if (input == null) return null;
		IEnumerable<XE_HR_REGIONS_IR>? retData;
		if (input.REGION_ID_IR_HasBeenChanged) retData = await GetByREGION_ID(input.REGION_ID_IR ?? default);
		else retData = await GetAll();
		return retData == null ? null : retData.Where(x => WhereAllFilledFields(x, input));
	}
	private static Boolean WhereAllFilledFields(XE_HR_REGIONS_IR record, XE_HR_REGIONS_IR filter)
	{
		 // unencrypted properties only
		return			(!filter.REGION_NAME_HasBeenChanged || record.REGION_NAME == filter.REGION_NAME);
	}
	public async Task<IEnumerable<XE_HR_REGIONS_IR>?> GetAll()
	{
		return await _hubConnection.InvokeAsync<IEnumerable<XE_HR_REGIONS_IR>?>("GetAll");
	}
	public async Task<IEnumerable<XE_HR_REGIONS_IR>?> GetByREGION_ID(String? rEGION_ID_IR)
	{
		return await _hubConnection.InvokeAsync<IEnumerable<XE_HR_REGIONS_IR>?>("GetByREGION_ID", rEGION_ID_IR);
	}
	public async Task<XE_HR_REGIONS_IR?> Create(XE_HR_REGIONS_IR input)
	{
		return await _hubConnection.InvokeAsync<XE_HR_REGIONS_IR?>("Create", input);
	}
	public async Task UpdateByEncodedPrimaryKey(String? encodedPrimaryKey, XE_HR_REGIONS_IR updateModel)
	{
		if (encodedPrimaryKey == null || updateModel == null) return;
		var inputSplits = encodedPrimaryKey.Split((Char)27);
		await UpdateByREGION_ID(inputSplits[0], updateModel);
	}
	public async Task UpdateByREGION_ID(String? rEGION_ID_IR, XE_HR_REGIONS_IR input)
	{
		await _hubConnection.InvokeAsync("UpdateByREGION_ID", rEGION_ID_IR, input);
	}
	public async Task DeleteByEncodedPrimaryKey(String? input)
	{
		if (input == null) return;
		var inputSplits = input.Split((Char)27);
		await DeleteByREGION_ID(inputSplits[0]);
	}
	public async Task DeleteByREGION_ID(String? rEGION_ID_IR)
	{
		await _hubConnection.InvokeAsync("DeleteByREGION_ID", rEGION_ID_IR);
	}
    public async Task InitializeAsync()
    {
        await base.EstablishConnection();
    }
    public Boolean GetStatus()
    {
        return base.Initiated;
    }
    public async ValueTask DisposeAsync()
    {
        await base.TerminateConnection();
        GC.SuppressFinalize(this);
    }
}
