/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307200434 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Standard Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using Northwind_BackEndDatabaseClient.Repositories;
using Northwind_BackEndSqlEntities.Entities;
namespace Northwind_BackEndCommon.RequestHandlers;
public interface INorthwind_dbo_Employees_RequestHandler
{
	//Main Handlers
	Task<IEnumerable<Northwind_dbo_Employees>?> HandleGetAll();
	Task<IEnumerable<Northwind_dbo_Employees>?> HandleGetByLastName(String lastName);
	Task<IEnumerable<Northwind_dbo_Employees>?> HandleGetByEmployeeID(Int32 employeeID);
	Task<IEnumerable<Northwind_dbo_Employees>?> HandleGetByPostalCode(String? postalCode);
	Task<Northwind_dbo_Employees?> HandleCreate(Northwind_dbo_Employees entity);
	Task HandleUpdateByLastName(String lastName, Northwind_dbo_Employees entity);
	Task HandleUpdateByEmployeeID(Int32 employeeID, Northwind_dbo_Employees entity);
	Task HandleUpdateByPostalCode(String? postalCode, Northwind_dbo_Employees entity);
	Task HandleDeleteByLastName(String lastName);
	Task HandleDeleteByEmployeeID(Int32 employeeID);
	Task HandleDeleteByPostalCode(String? postalCode);
}
