/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307200541 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using System.ComponentModel;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Northwind_Common.IndirectReferenceTransformerModels;
using Northwind_BackEndSqlEntities.Entities;
using Northwind_BackEndCommon.Services;
namespace Northwind_CommonTests.HydratedStaticIndirectReferenceTransformerModels;
public partial class Northwind_HydratedStaticIndirectReferenceTransformerModels : Northwind_HydratedStaticIndirectReferenceTransformerModelsBase
{
	public Northwind_dbo_Orders_Qry_IR GetHydratedStaticNorthwind_dbo_Orders_Qry_IR(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Orders_Qry_IR();
		retObj.OrderID_IR = (fillPrimaryKey ? _encryptionDecryptionService!.EncInt32(Convert.ToInt32(1)) : String.Empty);
		retObj.CustomerID = (fillPrimaryKey ? "bNKAG" : String.Empty);
		retObj.EmployeeID_IR = (fillPrimaryKey ? _encryptionDecryptionService!.EncInt32Nullable(Convert.ToInt32(1)) : String.Empty);
		retObj.OrderDate = DateTime.Parse("3/11/2013 12:00:00 AM");
		retObj.RequiredDate = DateTime.Parse("9/4/1999 12:00:00 AM");
		retObj.ShippedDate = DateTime.Parse("5/16/2015 12:00:00 AM");
		retObj.ShipVia = (-209821466);
		retObj.Freight = (0.30450373019588894M);
		retObj.ShipName = "p kQWjwOmY3EMXh pwb2Jt 6S9L1jI977I3Fockg";
		retObj.ShipAddress = "nGqqW7aFenQxVrh8M7CWt61SyjehK 9OM9k0eykiNwvpHWxiBLKDai4sg GK";
		retObj.ShipCity = "PSbUvqoFJT7K6F5";
		retObj.ShipRegion = "YEdgFADjiH9dihO";
		retObj.ShipPostalCode = "cD7YSvsOiI";
		retObj.ShipCountry = "W 2a4m2o 3TfJF8";
		retObj.CompanyName = "mCLCMlXjKnCRCoRtsPWOO5xihStWv1GOoCYaxdnG";
		retObj.Address = "obSMqRidP  I02LBWChVEI7oDikIvv2dydxecn06vqc0zxaWvKpdPdev4clP";
		retObj.City = "6Z9d2ZF1Z9Swj4w";
		retObj.Region = "1NtlV3NbZEnvlUG";
		retObj.PostalCode = "HAcegp0Z8l";
		retObj.Country = "f2M040xLmrN36Cd";
		return retObj;
	}
}
