/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307200636 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
// For reads only
using System.ComponentModel.DataAnnotations.Schema;
namespace Northwind_BackEndSqlEntities.Entities;
/// <summary>
/// SQL Entity Description: View Description: N/A
/// </summary>
public class Northwind_dbo_Invoices 
{
	public Northwind_dbo_Invoices()
	{
	} 
	public Northwind_dbo_Invoices(
		String? shipName_,
		String? shipAddress_,
		String? shipCity_,
		String? shipRegion_,
		String? shipPostalCode_,
		String? shipCountry_,
		String? customerID_,
		String customerName_,
		String? address_,
		String? city_,
		String? region_,
		String? postalCode_,
		String? country_,
		String salesperson_,
		Int32 orderID_,
		DateTime? orderDate_,
		DateTime? requiredDate_,
		DateTime? shippedDate_,
		String shipperName_,
		Int32 productID_,
		String productName_,
		Decimal unitPrice_,
		Int16 quantity_,
		Single discount_,
		Decimal? extendedPrice_,
		Decimal? freight_
	)
	{
		ShipName = shipName_;
		ShipAddress = shipAddress_;
		ShipCity = shipCity_;
		ShipRegion = shipRegion_;
		ShipPostalCode = shipPostalCode_;
		ShipCountry = shipCountry_;
		CustomerID = customerID_;
		CustomerName = customerName_;
		Address = address_;
		City = city_;
		Region = region_;
		PostalCode = postalCode_;
		Country = country_;
		Salesperson = salesperson_;
		OrderID = orderID_;
		OrderDate = orderDate_;
		RequiredDate = requiredDate_;
		ShippedDate = shippedDate_;
		ShipperName = shipperName_;
		ProductID = productID_;
		ProductName = productName_;
		UnitPrice = unitPrice_;
		Quantity = quantity_;
		Discount = discount_;
		ExtendedPrice = extendedPrice_;
		Freight = freight_;
	}
	/// <summary>
	/// SQL Data Type: nvarchar Chars: 40 
	/// SQL Column Description: N/A
	/// </summary>
	public virtual String? ShipName { get; set; }
	/// <summary>
	/// SQL Data Type: nvarchar Chars: 60 
	/// SQL Column Description: N/A
	/// </summary>
	public virtual String? ShipAddress { get; set; }
	/// <summary>
	/// SQL Data Type: nvarchar Chars: 15 
	/// SQL Column Description: N/A
	/// </summary>
	public virtual String? ShipCity { get; set; }
	/// <summary>
	/// SQL Data Type: nvarchar Chars: 15 
	/// SQL Column Description: N/A
	/// </summary>
	public virtual String? ShipRegion { get; set; }
	/// <summary>
	/// SQL Data Type: nvarchar Chars: 10 
	/// SQL Column Description: N/A
	/// </summary>
	public virtual String? ShipPostalCode { get; set; }
	/// <summary>
	/// SQL Data Type: nvarchar Chars: 15 
	/// SQL Column Description: N/A
	/// </summary>
	public virtual String? ShipCountry { get; set; }
	/// <summary>
	/// SQL Data Type: nchar Chars: 5 
	/// SQL Column Description: N/A
	/// </summary>
	public virtual String? CustomerID { get; set; }
	/// <summary>
	/// SQL Data Type: nvarchar Chars: 40 
	/// SQL Column Description: N/A
	/// </summary>
	public virtual String CustomerName { get; set; } = null!;
	/// <summary>
	/// SQL Data Type: nvarchar Chars: 60 
	/// SQL Column Description: N/A
	/// </summary>
	public virtual String? Address { get; set; }
	/// <summary>
	/// SQL Data Type: nvarchar Chars: 15 
	/// SQL Column Description: N/A
	/// </summary>
	public virtual String? City { get; set; }
	/// <summary>
	/// SQL Data Type: nvarchar Chars: 15 
	/// SQL Column Description: N/A
	/// </summary>
	public virtual String? Region { get; set; }
	/// <summary>
	/// SQL Data Type: nvarchar Chars: 10 
	/// SQL Column Description: N/A
	/// </summary>
	public virtual String? PostalCode { get; set; }
	/// <summary>
	/// SQL Data Type: nvarchar Chars: 15 
	/// SQL Column Description: N/A
	/// </summary>
	public virtual String? Country { get; set; }
	/// <summary>
	/// SQL Data Type: nvarchar Chars: 31 
	/// SQL Column Description: N/A
	/// </summary>
	public virtual String Salesperson { get; set; } = null!;
	/// <summary>
	/// SQL Data Type: int Precision: 10 Scale: 0 
	/// SQL Column Description: N/A
	/// </summary>
	public virtual Int32 OrderID { get; set; }
	/// <summary>
	/// SQL Data Type: datetime 
	/// SQL Column Description: N/A
	/// </summary>
	public virtual DateTime? OrderDate { get; set; }
	/// <summary>
	/// SQL Data Type: datetime 
	/// SQL Column Description: N/A
	/// </summary>
	public virtual DateTime? RequiredDate { get; set; }
	/// <summary>
	/// SQL Data Type: datetime 
	/// SQL Column Description: N/A
	/// </summary>
	public virtual DateTime? ShippedDate { get; set; }
	/// <summary>
	/// SQL Data Type: nvarchar Chars: 40 
	/// SQL Column Description: N/A
	/// </summary>
	public virtual String ShipperName { get; set; } = null!;
	/// <summary>
	/// SQL Data Type: int Precision: 10 Scale: 0 
	/// SQL Column Description: N/A
	/// </summary>
	public virtual Int32 ProductID { get; set; }
	/// <summary>
	/// SQL Data Type: nvarchar Chars: 40 
	/// SQL Column Description: N/A
	/// </summary>
	public virtual String ProductName { get; set; } = null!;
	/// <summary>
	/// SQL Data Type: money Precision: 19 Scale: 4 
	/// SQL Column Description: N/A
	/// </summary>
	public virtual Decimal UnitPrice { get; set; }
	/// <summary>
	/// SQL Data Type: smallint Precision: 5 Scale: 0 
	/// SQL Column Description: N/A
	/// </summary>
	public virtual Int16 Quantity { get; set; }
	/// <summary>
	/// SQL Data Type: real Precision: 24 
	/// SQL Column Description: N/A
	/// </summary>
	public virtual Single Discount { get; set; }
	/// <summary>
	/// SQL Data Type: money Precision: 19 Scale: 4 
	/// SQL Column Description: N/A
	/// </summary>
	public virtual Decimal? ExtendedPrice { get; set; }
	/// <summary>
	/// SQL Data Type: money Precision: 19 Scale: 4 
	/// SQL Column Description: N/A
	/// </summary>
	public virtual Decimal? Freight { get; set; }
}
