/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307200636 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Northwind_Common.IndirectReferenceTransformerModels;
namespace Northwind_BackEndCoreWCFServer.Services;
[ServiceContract]
public interface INorthwind_dbo_Orders_Service
{
	[OperationContract]
	Task<IEnumerable<Northwind_dbo_Orders_IR>?> GetAll();
	[OperationContract]
	Task<IEnumerable<Northwind_dbo_Orders_IR>?> GetByCustomerID(String? customerID);
	[OperationContract]
	Task<IEnumerable<Northwind_dbo_Orders_IR>?> GetByEmployeeID(String? employeeID_IR);
	[OperationContract]
	Task<IEnumerable<Northwind_dbo_Orders_IR>?> GetByOrderDate(DateTime? orderDate);
	[OperationContract]
	Task<IEnumerable<Northwind_dbo_Orders_IR>?> GetByOrderID(String? orderID_IR);
	[OperationContract]
	Task<IEnumerable<Northwind_dbo_Orders_IR>?> GetByShippedDate(DateTime? shippedDate);
	[OperationContract]
	Task<IEnumerable<Northwind_dbo_Orders_IR>?> GetByShipVia(String? shipVia_IR);
	[OperationContract]
	Task<IEnumerable<Northwind_dbo_Orders_IR>?> GetByShipPostalCode(String? shipPostalCode);
	[OperationContract]
	Task<Northwind_dbo_Orders_IR?> Create(Northwind_dbo_Orders_IR input);
	[OperationContract]
	Task UpdateByCustomerID(String? customerID, Northwind_dbo_Orders_IR input);
	[OperationContract]
	Task UpdateByEmployeeID(String? employeeID_IR, Northwind_dbo_Orders_IR input);
	[OperationContract]
	Task UpdateByOrderDate(DateTime? orderDate, Northwind_dbo_Orders_IR input);
	[OperationContract]
	Task UpdateByOrderID(String? orderID_IR, Northwind_dbo_Orders_IR input);
	[OperationContract]
	Task UpdateByShippedDate(DateTime? shippedDate, Northwind_dbo_Orders_IR input);
	[OperationContract]
	Task UpdateByShipVia(String? shipVia_IR, Northwind_dbo_Orders_IR input);
	[OperationContract]
	Task UpdateByShipPostalCode(String? shipPostalCode, Northwind_dbo_Orders_IR input);
	[OperationContract]
	Task DeleteByCustomerID(String? customerID);
	[OperationContract]
	Task DeleteByEmployeeID(String? employeeID_IR);
	[OperationContract]
	Task DeleteByOrderDate(DateTime? orderDate);
	[OperationContract]
	Task DeleteByOrderID(String? orderID_IR);
	[OperationContract]
	Task DeleteByShippedDate(DateTime? shippedDate);
	[OperationContract]
	Task DeleteByShipVia(String? shipVia_IR);
	[OperationContract]
	Task DeleteByShipPostalCode(String? shipPostalCode);
}
