/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307202958 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using XE_HR_BackEndSqlEntities.Entities;
namespace XE_HR_BackEndDatabaseClientTests.HydratedStaticEntities;
public partial class XE_HR_HydratedStaticEntities 
{
	public XE_HR_PACKAGE1_FUNCCONVERTDECIMALTOVARCHAR_OM GetHydratedStaticXE_HR_PACKAGE1_FUNCCONVERTDECIMALTOVARCHAR_OM(Boolean fillPrimaryKey = false)
	{
		var retObj = new XE_HR_PACKAGE1_FUNCCONVERTDECIMALTOVARCHAR_OM();
		// Output parameters
		retObj.FunctionReturnParam = "o1IS1tHCfLjvVsG4IAQmc rxriiarSPxoEGjMh4x68c1P9nZFe8G8ht1xAwP2xOuzZ aKiatXjooRMcMGD9GPhk9yTy0FMU31C5k";
		return retObj;
	}
}
