/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307200636 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
function getHydratedDynamicNorthwind_dbo_ProductsAndCategories(fillPrimaryKey = false) {
	var retObj = new Northwind_dbo_ProductsAndCategories_OM_IR();
	retObj.Query1_Results_IR.ToList().push({});
	retObj.query1_Results_IR[0].ProductID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.query1_Results[0].ProductName = generateString(40);
	retObj.query1_Results_IR[0].SupplierID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.query1_Results_IR[0].CategoryID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.query1_Results[0].QuantityPerUnit = generateString(20);
	retObj.query1_Results[0].UnitPrice = generateDecimal(19,4);
	retObj.query1_Results[0].UnitsInStock = generateInt16();
	retObj.query1_Results[0].UnitsOnOrder = generateInt16();
	retObj.query1_Results[0].ReorderLevel = generateInt16();
	retObj.query1_Results[0].Discontinued = generateBoolean();
	retObj.Query2_Results_IR.ToList().push({});
	retObj.query2_Results_IR[0].CategoryID_IR = (fillPrimaryKey ? encrypt(1) : null);
	retObj.query2_Results[0].CategoryName = generateString(15);
	retObj.query2_Results[0].Description = generateString(100);
	retObj.query2_Results[0].Picture = generateByteArray(100);
	return retObj;
}
