/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307200636 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Enterprise Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using System.ComponentModel;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Northwind_Common.IndirectReferenceTransformerModels;
using Northwind_BackEndSqlEntities.Entities;
using Northwind_BackEndCommon.Services;
namespace Northwind_CommonTests.HydratedStaticIndirectReferenceTransformerModels;
public partial class Northwind_HydratedStaticIndirectReferenceTransformerModels : Northwind_HydratedStaticIndirectReferenceTransformerModelsBase
{
	public Northwind_dbo_Employee_Sales_by_Country_OM_IR GetHydratedStaticNorthwind_dbo_Employee_Sales_by_Country_OM_IR(Boolean fillPrimaryKey = false)
	{
		var retObj = new Northwind_dbo_Employee_Sales_by_Country_OM_IR();
		retObj.Country = "3g6fmR0m6CRzB90";
		retObj.LastName = "W18HL36NNmy7nNEW1O8G";
		retObj.FirstName = "RxIDkSmrKA";
		retObj.ShippedDate = DateTime.Parse("12/28/1995 12:00:00 AM");
		retObj.OrderID_IR = _encryptionDecryptionService!.EncInt32(Convert.ToInt32(1));
		retObj.SaleAmount = (0.8735926887571616M);
		return retObj;
	}
}
