echo "You must have the CLI tooling called dotnet-svcutil installed on this machine to run this batch file."
echo "To install the tooling, run the following command in a terminal: dotnet tool install --global dotnet-svcutil"
echo "Start up the debugger on the CoreWCFServer project before running this batch file."
echo "You must have the CLI tooling called dotnet-svcutil installed on this machine to run this batch file."
echo "Once this script completes, Add the project found at ../FrontEndCoreWCFClientTests/XE_HR_FrontEndCoreWCFClientTests.csproj to this solution."
dotnet-svcutil https://localhost:5001/XE_HR_COUNTRIES_Service?wsdl -d CoreWCFClients -n "*,XE_HR_FrontEndCoreWCFClient.CoreWCFClients" -o "XE_HR_COUNTRIES_WCFClient" -r "../Common/XE_HR_Common.csproj" -ser DataContractSerializer -ac
dotnet-svcutil https://localhost:5001/XE_HR_DEPARTMENTS_Service?wsdl -d CoreWCFClients -n "*,XE_HR_FrontEndCoreWCFClient.CoreWCFClients" -o "XE_HR_DEPARTMENTS_WCFClient" -r "../Common/XE_HR_Common.csproj" -ser DataContractSerializer -ac
dotnet-svcutil https://localhost:5001/XE_HR_EMPLOYEES_Service?wsdl -d CoreWCFClients -n "*,XE_HR_FrontEndCoreWCFClient.CoreWCFClients" -o "XE_HR_EMPLOYEES_WCFClient" -r "../Common/XE_HR_Common.csproj" -ser DataContractSerializer -ac
dotnet-svcutil https://localhost:5001/XE_HR_JOB_HISTORY_Service?wsdl -d CoreWCFClients -n "*,XE_HR_FrontEndCoreWCFClient.CoreWCFClients" -o "XE_HR_JOB_HISTORY_WCFClient" -r "../Common/XE_HR_Common.csproj" -ser DataContractSerializer -ac
dotnet-svcutil https://localhost:5001/XE_HR_JOBS_Service?wsdl -d CoreWCFClients -n "*,XE_HR_FrontEndCoreWCFClient.CoreWCFClients" -o "XE_HR_JOBS_WCFClient" -r "../Common/XE_HR_Common.csproj" -ser DataContractSerializer -ac
dotnet-svcutil https://localhost:5001/XE_HR_LOCATIONS_Service?wsdl -d CoreWCFClients -n "*,XE_HR_FrontEndCoreWCFClient.CoreWCFClients" -o "XE_HR_LOCATIONS_WCFClient" -r "../Common/XE_HR_Common.csproj" -ser DataContractSerializer -ac
dotnet-svcutil https://localhost:5001/XE_HR_REGIONS_Service?wsdl -d CoreWCFClients -n "*,XE_HR_FrontEndCoreWCFClient.CoreWCFClients" -o "XE_HR_REGIONS_WCFClient" -r "../Common/XE_HR_Common.csproj" -ser DataContractSerializer -ac
dotnet-svcutil https://localhost:5001/XE_HR_EMP_DETAILS_VIEW_Service?wsdl -d CoreWCFClients -n "*,XE_HR_FrontEndCoreWCFClient.CoreWCFClients" -o "XE_HR_EMP_DETAILS_VIEW_WCFClient" -r "../Common/XE_HR_Common.csproj" -ser DataContractSerializer -ac
dotnet-svcutil https://localhost:5001/XE_HR_PACKAGE1_FUNCCONVERTDECIMALTOVARCHAR_StoredProcedure_Service?wsdl -d CoreWCFClients -n "*,XE_HR_FrontEndCoreWCFClient.CoreWCFClients" -o "XE_HR_PACKAGE1_FUNCCONVERTDECIMALTOVARCHAR_StoredProcedure_WCFClient" -r "../Common/XE_HR_Common.csproj" -ser DataContractSerializer -ac
dotnet-svcutil https://localhost:5001/XE_HR_PACKAGE1_OPEN_ONE_CURSOR_StoredProcedure_Service?wsdl -d CoreWCFClients -n "*,XE_HR_FrontEndCoreWCFClient.CoreWCFClients" -o "XE_HR_PACKAGE1_OPEN_ONE_CURSOR_StoredProcedure_WCFClient" -r "../Common/XE_HR_Common.csproj" -ser DataContractSerializer -ac
dotnet-svcutil https://localhost:5001/XE_HR_PACKAGE1_OPEN_TWO_CURSORS_StoredProcedure_Service?wsdl -d CoreWCFClients -n "*,XE_HR_FrontEndCoreWCFClient.CoreWCFClients" -o "XE_HR_PACKAGE1_OPEN_TWO_CURSORS_StoredProcedure_WCFClient" -r "../Common/XE_HR_Common.csproj" -ser DataContractSerializer -ac
dotnet-svcutil https://localhost:5001/XE_HR_PACKAGE1_PARAMOUTCURSORS_StoredProcedure_Service?wsdl -d CoreWCFClients -n "*,XE_HR_FrontEndCoreWCFClient.CoreWCFClients" -o "XE_HR_PACKAGE1_PARAMOUTCURSORS_StoredProcedure_WCFClient" -r "../Common/XE_HR_Common.csproj" -ser DataContractSerializer -ac
dotnet-svcutil https://localhost:5001/XE_HR_PACKAGE1_RETURNSTRINGPROC_StoredProcedure_Service?wsdl -d CoreWCFClients -n "*,XE_HR_FrontEndCoreWCFClient.CoreWCFClients" -o "XE_HR_PACKAGE1_RETURNSTRINGPROC_StoredProcedure_WCFClient" -r "../Common/XE_HR_Common.csproj" -ser DataContractSerializer -ac
