/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307202926 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using Microsoft.EntityFrameworkCore;
using System.ComponentModel;
using Newtonsoft.Json;
using XE_HR_Common.IndirectReferenceTransformerModels;
using XE_HR_BackEndCommon.Configuration;
using XE_HR_BackEndSqlEntities.Entities;
using XE_HR_BackEndCommon.Services;
namespace XE_HR_CommonTests.HydratedStaticIndirectReferenceTransformerModels;
public class XE_HR_HydratedStaticIndirectReferenceTransformerModelsBase
{
	protected readonly CustomAppSettings? _customAppSettings;
	protected readonly IEncryptionDecryptionService? _encryptionDecryptionService;
	public XE_HR_HydratedStaticIndirectReferenceTransformerModelsBase()
	{
		_customAppSettings = JsonConvert.DeserializeObject<CustomAppSettings>(File.ReadAllText(Path.Combine(Directory.GetCurrentDirectory(), "appSettings.Test.json")));
		_encryptionDecryptionService = new EncryptionDecryptionService(_customAppSettings!.EncryptDecryptKey!);
	}
}
