/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307202926 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using System.ComponentModel;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using XE_HR_Common.IndirectReferenceTransformerModels;
using XE_HR_BackEndSqlEntities.Entities;
using XE_HR_BackEndCommon.Services;
namespace XE_HR_CommonTests.HydratedStaticIndirectReferenceTransformerModels;
public partial class XE_HR_HydratedStaticIndirectReferenceTransformerModels : XE_HR_HydratedStaticIndirectReferenceTransformerModelsBase
{
	public XE_HR_DEPARTMENTS_IR GetHydratedStaticXE_HR_DEPARTMENTS_IR(Boolean fillPrimaryKey = false)
	{
		var retObj = new XE_HR_DEPARTMENTS_IR();
		retObj.DEPARTMENT_ID_IR = (fillPrimaryKey ? _encryptionDecryptionService!.EncInt32(Convert.ToInt32(1)) : String.Empty);
		retObj.DEPARTMENT_NAME = "wTUdfUroaQREWyKVj8oYmCjSedi6 h";
		retObj.MANAGER_ID_IR = _encryptionDecryptionService!.EncInt32Nullable(Convert.ToInt32(1));
		retObj.LOCATION_ID_IR = _encryptionDecryptionService!.EncInt32Nullable(Convert.ToInt32(1));
		// Foreign key entities
		retObj.DEPT_LOC_FK_Ref_IR = GetHydratedStaticXE_HR_LOCATIONS_IR();
		retObj.DEPT_MGR_FK_Ref_IR = GetHydratedStaticXE_HR_EMPLOYEES_IR();
		return retObj;
	}
}
