/* **** This file and its contents were generated by YouGen Sharp on (UTC) 20230307200541 on behalf of: ****
**** You Gen Software LLC ****
**** 5961 BeaconPark St ****
**** Lithia Florida 33547 United States of America ****
**** whose account is uniquely identified by: 716881407 ****
**** This file and its contents are subject to the conditions of use for the Professional Tier License as specified at: https://www.yougensoft.com/en/conditions-of-use. ****
**** This comment block must not be removed. ****
 */
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;
namespace Northwind_Common.IndirectReferenceTransformerModels;
/// <summary>
/// Sql Entity Description: Indirect Referenced Model Description: N/A
/// </summary>
public class Northwind_dbo_Region_IR
{
	public Northwind_dbo_Region_IR() 
	{
	} 
	public Northwind_dbo_Region_IR(
		String? regionID_IR_,
		String? regionDescription_
	)
	{
		_regionID_IR = regionID_IR_;
		RegionID_IR_OriginalValue = regionID_IR_;
		_regionDescription = regionDescription_;
		RegionDescription_OriginalValue = regionDescription_;
		PrimaryKeyEncryptedForUpdateDeleteIdentification = regionID_IR_;
	}
	[JsonConstructor]
	public Northwind_dbo_Region_IR(
		String? RegionID_IR,
		String? RegionID_IR_OriginalValue,
		Boolean RegionID_IR_HasBeenChanged,
		String RegionDescription,
		String RegionDescription_OriginalValue,
		Boolean RegionDescription_HasBeenChanged,
		String? PrimaryKeyEncryptedForUpdateDeleteIdentification,
		String? PrimaryKeyHashedForUniqueObjectComparison
	)
	{
		this.RegionID_IR = RegionID_IR;
		this.RegionID_IR_OriginalValue = RegionID_IR_OriginalValue;
		this.RegionID_IR_HasBeenChanged = RegionID_IR_HasBeenChanged;
		this.RegionDescription = RegionDescription;
		this.RegionDescription_OriginalValue = RegionDescription_OriginalValue;
		this.RegionDescription_HasBeenChanged = RegionDescription_HasBeenChanged;
		this.PrimaryKeyEncryptedForUpdateDeleteIdentification = PrimaryKeyEncryptedForUpdateDeleteIdentification;
		this.PrimaryKeyHashedForUniqueObjectComparison = PrimaryKeyHashedForUniqueObjectComparison;
	}
	/// <summary>
	/// SQL Column Description: Primary key encrypted value for update and delete identification purposes
	/// </summary>
	public String? PrimaryKeyEncryptedForUpdateDeleteIdentification { get; set; }
	/// <summary>
	/// SQL Column Description: Primary key hashed value for uniue object comparison purposes
	/// </summary>
	public String? PrimaryKeyHashedForUniqueObjectComparison { get; set; }
	/// <summary>
	/// SQL Column Description: N/A
	/// </summary>
	public String? RegionID_IR
	{
		get => _regionID_IR;
		set
		{
			_regionID_IR = value;
			RegionID_IR_HasBeenChanged = _regionID_IR == RegionID_IR_OriginalValue ? false : true;
		}
	}
	private String? _regionID_IR;
	public String? RegionID_IR_OriginalValue { get; private set; }
	public Boolean RegionID_IR_HasBeenChanged { get; private set; }
	/// <summary>
	/// SQL Column Description: N/A
	/// </summary>
	public String? RegionDescription
	{
		get => _regionDescription;
		set
		{
			_regionDescription = value;
			RegionDescription_HasBeenChanged = _regionDescription == RegionDescription_OriginalValue ? false : true;
		}
	}
	private String? _regionDescription;
	public String? RegionDescription_OriginalValue  { get; private set; }
	public Boolean RegionDescription_HasBeenChanged  { get; private set; }
	/// <summary>
	/// Entities that reference this entity by foreign key
	/// </summary>
	/// <example>null</example>
	public virtual ICollection<Northwind_dbo_Territories_IR>?FK_Territories_Region_RefBy_IR { get; set; } = new HashSet<Northwind_dbo_Territories_IR>();
}
