//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XE_HR_FrontEndCoreWCFClient.CoreWCFClients
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="XE_HR_FrontEndCoreWCFClient.CoreWCFClients.IXE_HR_JOB_HISTORY_Service")]
    public interface IXE_HR_JOB_HISTORY_Service
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXE_HR_JOB_HISTORY_Service/GetAll", ReplyAction="http://tempuri.org/IXE_HR_JOB_HISTORY_Service/GetAllResponse")]
        System.Threading.Tasks.Task<XE_HR_Common.IndirectReferenceTransformerModels.XE_HR_JOB_HISTORY_IR[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXE_HR_JOB_HISTORY_Service/GetByEMPLOYEE_IDAndSTART_DATE", ReplyAction="http://tempuri.org/IXE_HR_JOB_HISTORY_Service/GetByEMPLOYEE_IDAndSTART_DATERespon" +
            "se")]
        System.Threading.Tasks.Task<XE_HR_Common.IndirectReferenceTransformerModels.XE_HR_JOB_HISTORY_IR[]> GetByEMPLOYEE_IDAndSTART_DATEAsync(string eMPLOYEE_ID_IR, System.DateTime sTART_DATE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXE_HR_JOB_HISTORY_Service/GetByDEPARTMENT_ID", ReplyAction="http://tempuri.org/IXE_HR_JOB_HISTORY_Service/GetByDEPARTMENT_IDResponse")]
        System.Threading.Tasks.Task<XE_HR_Common.IndirectReferenceTransformerModels.XE_HR_JOB_HISTORY_IR[]> GetByDEPARTMENT_IDAsync(string dEPARTMENT_ID_IR);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXE_HR_JOB_HISTORY_Service/GetByEMPLOYEE_ID", ReplyAction="http://tempuri.org/IXE_HR_JOB_HISTORY_Service/GetByEMPLOYEE_IDResponse")]
        System.Threading.Tasks.Task<XE_HR_Common.IndirectReferenceTransformerModels.XE_HR_JOB_HISTORY_IR[]> GetByEMPLOYEE_IDAsync(string eMPLOYEE_ID_IR);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXE_HR_JOB_HISTORY_Service/GetByJOB_ID", ReplyAction="http://tempuri.org/IXE_HR_JOB_HISTORY_Service/GetByJOB_IDResponse")]
        System.Threading.Tasks.Task<XE_HR_Common.IndirectReferenceTransformerModels.XE_HR_JOB_HISTORY_IR[]> GetByJOB_IDAsync(string jOB_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXE_HR_JOB_HISTORY_Service/Create", ReplyAction="http://tempuri.org/IXE_HR_JOB_HISTORY_Service/CreateResponse")]
        System.Threading.Tasks.Task<XE_HR_Common.IndirectReferenceTransformerModels.XE_HR_JOB_HISTORY_IR> CreateAsync(XE_HR_Common.IndirectReferenceTransformerModels.XE_HR_JOB_HISTORY_IR input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXE_HR_JOB_HISTORY_Service/UpdateByEMPLOYEE_IDAndSTART_DATE", ReplyAction="http://tempuri.org/IXE_HR_JOB_HISTORY_Service/UpdateByEMPLOYEE_IDAndSTART_DATERes" +
            "ponse")]
        System.Threading.Tasks.Task UpdateByEMPLOYEE_IDAndSTART_DATEAsync(string eMPLOYEE_ID_IR, System.DateTime sTART_DATE, XE_HR_Common.IndirectReferenceTransformerModels.XE_HR_JOB_HISTORY_IR input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXE_HR_JOB_HISTORY_Service/UpdateByDEPARTMENT_ID", ReplyAction="http://tempuri.org/IXE_HR_JOB_HISTORY_Service/UpdateByDEPARTMENT_IDResponse")]
        System.Threading.Tasks.Task UpdateByDEPARTMENT_IDAsync(string dEPARTMENT_ID_IR, XE_HR_Common.IndirectReferenceTransformerModels.XE_HR_JOB_HISTORY_IR input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXE_HR_JOB_HISTORY_Service/UpdateByEMPLOYEE_ID", ReplyAction="http://tempuri.org/IXE_HR_JOB_HISTORY_Service/UpdateByEMPLOYEE_IDResponse")]
        System.Threading.Tasks.Task UpdateByEMPLOYEE_IDAsync(string eMPLOYEE_ID_IR, XE_HR_Common.IndirectReferenceTransformerModels.XE_HR_JOB_HISTORY_IR input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXE_HR_JOB_HISTORY_Service/UpdateByJOB_ID", ReplyAction="http://tempuri.org/IXE_HR_JOB_HISTORY_Service/UpdateByJOB_IDResponse")]
        System.Threading.Tasks.Task UpdateByJOB_IDAsync(string jOB_ID, XE_HR_Common.IndirectReferenceTransformerModels.XE_HR_JOB_HISTORY_IR input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXE_HR_JOB_HISTORY_Service/DeleteByEMPLOYEE_IDAndSTART_DATE", ReplyAction="http://tempuri.org/IXE_HR_JOB_HISTORY_Service/DeleteByEMPLOYEE_IDAndSTART_DATERes" +
            "ponse")]
        System.Threading.Tasks.Task DeleteByEMPLOYEE_IDAndSTART_DATEAsync(string eMPLOYEE_ID_IR, System.DateTime sTART_DATE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXE_HR_JOB_HISTORY_Service/DeleteByDEPARTMENT_ID", ReplyAction="http://tempuri.org/IXE_HR_JOB_HISTORY_Service/DeleteByDEPARTMENT_IDResponse")]
        System.Threading.Tasks.Task DeleteByDEPARTMENT_IDAsync(string dEPARTMENT_ID_IR);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXE_HR_JOB_HISTORY_Service/DeleteByEMPLOYEE_ID", ReplyAction="http://tempuri.org/IXE_HR_JOB_HISTORY_Service/DeleteByEMPLOYEE_IDResponse")]
        System.Threading.Tasks.Task DeleteByEMPLOYEE_IDAsync(string eMPLOYEE_ID_IR);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXE_HR_JOB_HISTORY_Service/DeleteByJOB_ID", ReplyAction="http://tempuri.org/IXE_HR_JOB_HISTORY_Service/DeleteByJOB_IDResponse")]
        System.Threading.Tasks.Task DeleteByJOB_IDAsync(string jOB_ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IXE_HR_JOB_HISTORY_ServiceChannel : XE_HR_FrontEndCoreWCFClient.CoreWCFClients.IXE_HR_JOB_HISTORY_Service, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class XE_HR_JOB_HISTORY_ServiceClient : System.ServiceModel.ClientBase<XE_HR_FrontEndCoreWCFClient.CoreWCFClients.IXE_HR_JOB_HISTORY_Service>, XE_HR_FrontEndCoreWCFClient.CoreWCFClients.IXE_HR_JOB_HISTORY_Service
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public XE_HR_JOB_HISTORY_ServiceClient() : 
                base(XE_HR_JOB_HISTORY_ServiceClient.GetDefaultBinding(), XE_HR_JOB_HISTORY_ServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IXE_HR_JOB_HISTORY_Service.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public XE_HR_JOB_HISTORY_ServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(XE_HR_JOB_HISTORY_ServiceClient.GetBindingForEndpoint(endpointConfiguration), XE_HR_JOB_HISTORY_ServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public XE_HR_JOB_HISTORY_ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(XE_HR_JOB_HISTORY_ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public XE_HR_JOB_HISTORY_ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(XE_HR_JOB_HISTORY_ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public XE_HR_JOB_HISTORY_ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<XE_HR_Common.IndirectReferenceTransformerModels.XE_HR_JOB_HISTORY_IR[]> GetAllAsync()
        {
            return base.Channel.GetAllAsync();
        }
        
        public System.Threading.Tasks.Task<XE_HR_Common.IndirectReferenceTransformerModels.XE_HR_JOB_HISTORY_IR[]> GetByEMPLOYEE_IDAndSTART_DATEAsync(string eMPLOYEE_ID_IR, System.DateTime sTART_DATE)
        {
            return base.Channel.GetByEMPLOYEE_IDAndSTART_DATEAsync(eMPLOYEE_ID_IR, sTART_DATE);
        }
        
        public System.Threading.Tasks.Task<XE_HR_Common.IndirectReferenceTransformerModels.XE_HR_JOB_HISTORY_IR[]> GetByDEPARTMENT_IDAsync(string dEPARTMENT_ID_IR)
        {
            return base.Channel.GetByDEPARTMENT_IDAsync(dEPARTMENT_ID_IR);
        }
        
        public System.Threading.Tasks.Task<XE_HR_Common.IndirectReferenceTransformerModels.XE_HR_JOB_HISTORY_IR[]> GetByEMPLOYEE_IDAsync(string eMPLOYEE_ID_IR)
        {
            return base.Channel.GetByEMPLOYEE_IDAsync(eMPLOYEE_ID_IR);
        }
        
        public System.Threading.Tasks.Task<XE_HR_Common.IndirectReferenceTransformerModels.XE_HR_JOB_HISTORY_IR[]> GetByJOB_IDAsync(string jOB_ID)
        {
            return base.Channel.GetByJOB_IDAsync(jOB_ID);
        }
        
        public System.Threading.Tasks.Task<XE_HR_Common.IndirectReferenceTransformerModels.XE_HR_JOB_HISTORY_IR> CreateAsync(XE_HR_Common.IndirectReferenceTransformerModels.XE_HR_JOB_HISTORY_IR input)
        {
            return base.Channel.CreateAsync(input);
        }
        
        public System.Threading.Tasks.Task UpdateByEMPLOYEE_IDAndSTART_DATEAsync(string eMPLOYEE_ID_IR, System.DateTime sTART_DATE, XE_HR_Common.IndirectReferenceTransformerModels.XE_HR_JOB_HISTORY_IR input)
        {
            return base.Channel.UpdateByEMPLOYEE_IDAndSTART_DATEAsync(eMPLOYEE_ID_IR, sTART_DATE, input);
        }
        
        public System.Threading.Tasks.Task UpdateByDEPARTMENT_IDAsync(string dEPARTMENT_ID_IR, XE_HR_Common.IndirectReferenceTransformerModels.XE_HR_JOB_HISTORY_IR input)
        {
            return base.Channel.UpdateByDEPARTMENT_IDAsync(dEPARTMENT_ID_IR, input);
        }
        
        public System.Threading.Tasks.Task UpdateByEMPLOYEE_IDAsync(string eMPLOYEE_ID_IR, XE_HR_Common.IndirectReferenceTransformerModels.XE_HR_JOB_HISTORY_IR input)
        {
            return base.Channel.UpdateByEMPLOYEE_IDAsync(eMPLOYEE_ID_IR, input);
        }
        
        public System.Threading.Tasks.Task UpdateByJOB_IDAsync(string jOB_ID, XE_HR_Common.IndirectReferenceTransformerModels.XE_HR_JOB_HISTORY_IR input)
        {
            return base.Channel.UpdateByJOB_IDAsync(jOB_ID, input);
        }
        
        public System.Threading.Tasks.Task DeleteByEMPLOYEE_IDAndSTART_DATEAsync(string eMPLOYEE_ID_IR, System.DateTime sTART_DATE)
        {
            return base.Channel.DeleteByEMPLOYEE_IDAndSTART_DATEAsync(eMPLOYEE_ID_IR, sTART_DATE);
        }
        
        public System.Threading.Tasks.Task DeleteByDEPARTMENT_IDAsync(string dEPARTMENT_ID_IR)
        {
            return base.Channel.DeleteByDEPARTMENT_IDAsync(dEPARTMENT_ID_IR);
        }
        
        public System.Threading.Tasks.Task DeleteByEMPLOYEE_IDAsync(string eMPLOYEE_ID_IR)
        {
            return base.Channel.DeleteByEMPLOYEE_IDAsync(eMPLOYEE_ID_IR);
        }
        
        public System.Threading.Tasks.Task DeleteByJOB_IDAsync(string jOB_ID)
        {
            return base.Channel.DeleteByJOB_IDAsync(jOB_ID);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IXE_HR_JOB_HISTORY_Service))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IXE_HR_JOB_HISTORY_Service))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:5001/XE_HR_JOB_HISTORY_Service");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return XE_HR_JOB_HISTORY_ServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IXE_HR_JOB_HISTORY_Service);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return XE_HR_JOB_HISTORY_ServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IXE_HR_JOB_HISTORY_Service);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IXE_HR_JOB_HISTORY_Service,
        }
    }
}
